"use client";

import { useMemo, useRef, useState } from "react";

type Access = "Public" | "Internal" | "Confidential" | "Restricted";
type RecordItem = { id:string; name:string; format:string; pages:number; size:string; office:string; access:Access; status:string; confidence:number; excerpt:string; tags:string[]; updated:string };

const seed:RecordItem[] = [
  {id:"OSE-2026-00418",name:"Middle Rio Grande Water Rights Abstract.pdf",format:"PDF",pages:146,size:"18.4 MB",office:"WRAP",access:"Internal",status:"Available",confidence:99.2,excerpt:"Declared and permitted rights within the Middle Rio Grande administrative basin, indexed by owner, parcel and point of diversion.",tags:["water rights","MRG","abstract"],updated:"8 min ago"},
  {id:"OSE-2026-00417",name:"RG-89214 Change of Location Application.tif",format:"TIFF",pages:28,size:"42.8 MB",office:"District I",access:"Confidential",status:"OCR",confidence:94.7,excerpt:"Scanned application and supporting exhibits. Handwriting recognition and quality review are in progress.",tags:["application","change","RG-89214"],updated:"11 min ago"},
  {id:"OSE-2026-00416",name:"Hydrographic Survey Field Notes.zip",format:"ZIP",pages:311,size:"96.1 MB",office:"Hydrology",access:"Internal",status:"Indexing",confidence:97.8,excerpt:"Archive expanded into 84 images, 17 PDFs, three spreadsheets and associated GIS metadata.",tags:["survey","field notes","archive"],updated:"18 min ago"},
  {id:"OSE-2026-00415",name:"Acequia Association Correspondence 1978–1984.pdf",format:"PDF",pages:224,size:"31.6 MB",office:"Archives",access:"Public",status:"Available",confidence:98.6,excerpt:"Digitized correspondence concerning delivery schedules, maintenance, membership and historical use.",tags:["acequia","historical","correspondence"],updated:"36 min ago"},
  {id:"OSE-2026-00414",name:"Well Log SJ-10482.jpg",format:"JPG",pages:1,size:"4.2 MB",office:"District V",access:"Restricted",status:"Review",confidence:88.1,excerpt:"Potential sensitive personal information detected. Awaiting records administrator review.",tags:["well log","SJ-10482","review"],updated:"1 hr ago"}
];

const roleAccess:Record<string,Access[]> = {"Records Administrator":["Public","Internal","Confidential","Restricted"],"Program Analyst":["Public","Internal","Confidential"],"Public Viewer":["Public"]};
const I=({children}:{children:React.ReactNode})=><span className="icon">{children}</span>;

export default function Home(){
  const [records,setRecords]=useState(seed),[query,setQuery]=useState(""),[scope,setScope]=useState("All collections"),[role,setRole]=useState("Records Administrator"),[modal,setModal]=useState(false),[detail,setDetail]=useState<RecordItem|null>(null),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[drag,setDrag]=useState(false);
  const picker=useRef<HTMLInputElement>(null);
  const visible=useMemo(()=>records.filter(r=>roleAccess[role].includes(r.access)&&(scope==="All collections"||r.office===scope)&&`${r.name} ${r.id} ${r.office} ${r.excerpt} ${r.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[records,query,scope,role]);
  const choose=(list:FileList|null)=>{if(!list?.length)return;setFiles(Array.from(list));setModal(true)};
  const ingest=async()=>{setBusy(true);await new Promise(r=>setTimeout(r,900));const additions=files.map((f,i):RecordItem=>({id:`OSE-2026-${String(419+records.length+i).padStart(5,"0")}`,name:f.name,format:f.name.split(".").pop()?.toUpperCase()||"FILE",pages:f.name.toLowerCase().endsWith(".zip")?0:1,size:f.size>1e6?`${(f.size/1e6).toFixed(1)} MB`:`${Math.max(1,Math.round(f.size/1000))} KB`,office:"Ingestion Queue",access:"Internal",status:f.name.toLowerCase().endsWith(".zip")?"Expanding":"OCR",confidence:0,excerpt:f.name.toLowerCase().endsWith(".zip")?"Archive registered for checksum validation, secure expansion, inventory and malware screening.":"Object registered. OCR, image analysis, metadata extraction and classification are queued.",tags:["new intake",f.name.toLowerCase().endsWith(".zip")?"archive":"OCR queued"],updated:"just now"}));setRecords(r=>[...additions,...r]);setBusy(false);setModal(false);setFiles([])};
  return <main>
    <header><div className="brand"><div className="seal">W</div><div><b>WATERS</b><small>INTELLIGENT INGESTION ENGINE</small></div></div><nav><button className="active">▦ Command</button><button>▱ Catalog</button><button>⌁ Pipeline</button><button>◇ Governance</button></nav><div className="identity"><span>● SYSTEM SECURE</span><select value={role} onChange={e=>setRole(e.target.value)}>{Object.keys(roleAccess).map(x=><option key={x}>{x}</option>)}</select><i>GL</i></div></header>
    <section className="hero"><div><label>UNIVERSAL RECORDS INTELLIGENCE</label><h1>Every document.<br/><em>Understood.</em></h1><p>Securely ingest, recognize, catalog and discover the complete institutional record—governed by identity, role and purpose.</p></div><aside>{[["2.84M","Objects indexed"],["98.7%","OCR confidence"],["14.2s","Median ingestion"]].map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span><small>● operational</small></div>)}</aside></section>
    <section className="search"><div className="searchbox"><I>⌕</I><input aria-label="Universal search" placeholder="Search every authorized record, phrase, parcel, owner, case or concept…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd><button>Search</button></div><div className="scopes"><small>SEARCH SCOPE</small>{["All collections","WRAP","Hydrology","Archives","District I"].map(x=><button onClick={()=>setScope(x)} className={scope===x?"on":""} key={x}>{x}</button>)}<span>▣ Results filtered for {role}</span></div></section>
    <section className="work"><aside className="intake"><div className="cap"><b>⇧ INTAKE</b><span>FREE-TIER PROTOTYPE</span></div><div className={`drop ${drag?"drag":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files)}}><div className="upload">⇧</div><h2>Drop anything here</h2><p>Files, folders or ZIP archives</p><button onClick={()=>picker.current?.click()}>Choose files</button><input ref={picker} hidden type="file" multiple onChange={e=>choose(e.target.files)}/><small>PDF · TIFF · DOCX · XLSX · IMAGES · ZIP<br/>Files remain governed through the intake pipeline</small></div><div className="steps">{[["✓","Secure intake","Type, checksum & malware inspection"],["02","OCR + vision","Text, layout & handwriting"],["03","Classify + catalog","Metadata & retention policy"],["04","Authorize + index","RBAC-aware universal search"]].map(([n,a,b])=><div key={n}><i>{n}</i><p><b>{a}</b><small>{b}</small></p></div>)}</div></aside>
      <section className="catalog"><div className="catalogHead"><div><label>AUTHORIZED CATALOG</label><h2>{query?`Results for “${query}”`:"Recently ingested"}</h2><p>{visible.length} visible records · {records.length-visible.length} excluded by access or filters</p></div><small><i/> AVAILABLE　 <i className="amber"/> PROCESSING　 <i className="red"/> REVIEW</small></div><div className="list">{visible.map(r=><article key={r.id} onClick={()=>setDetail(r)}><div className={`file ${r.format.toLowerCase()}`}>▤<small>{r.format}</small></div><div className="copy"><div><span>{r.id}</span><b className={`status ${r.status.toLowerCase()}`}>{r.status}</b><b className="access">▣ {r.access}</b></div><h3>{r.name}</h3><p>{r.excerpt}</p><footer>{r.tags.map(t=><span key={t}>{t}</span>)}</footer></div><div className="meta"><b>{r.confidence?`${r.confidence}%`:"Queued"}</b><small>{r.confidence?"OCR confidence":"Processing"}</small><span>{r.pages||"—"} pages · {r.size}</span><span>{r.office} · {r.updated}</span></div></article>)}</div></section>
    </section>
    <section className="waters-doctrine"><div><label>THE ZIAWOLF WAY · INSTITUTIONAL MEMORY</label><h2>The record is the riverbed.</h2><p>Preserve the source. Govern the current. Protect everything downstream. WATERS turns documents into trusted institutional intelligence without surrendering provenance, human authority or public accountability.</p></div><aside>{[["01","PROVENANCE","Every object retains source, custody and history."],["02","AUTHORITY","Access follows identity, role and lawful purpose."],["03","CONSEQUENCE","AI assists; accountable people decide."]].map(([n,a,b])=><article key={n}><span>{n}</span><b>{a}</b><small>{b}</small></article>)}</aside></section>
    <footer className="global"><span>WATERS · Office of the State Engineer modernization concept</span><span><a href="/waters-modernization-brief.html">Public modernization brief</a> · <a href="/waters-modernization-archive.html">Archive</a></span><span>◇ Zero-trust access · Encryption · Complete audit trail</span></footer>
    {modal&&<div className="overlay" onMouseDown={()=>!busy&&setModal(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}>×</button><label>NEW INTAKE BATCH</label><h2>Review upload</h2><div className="queue">{files.map(f=><div key={f.name+f.size}>▤<p><b>{f.name}</b><small>{f.size>1e6?`${(f.size/1e6).toFixed(1)} MB`:`${Math.round(f.size/1000)} KB`} · classification pending</small></p><span>READY</span></div>)}</div><div className="govern">◇ <p><b>Governed ingestion</b><small>Every object receives a checksum, audit event, retention review and access policy before discovery.</small></p></div><button className="primary" onClick={ingest} disabled={busy}>{busy?"Registering intake…":`Start intelligent ingestion · ${files.length} object${files.length===1?"":"s"}`}</button></section></div>}
    {detail&&<div className="overlay drawerWrap" onClick={()=>setDetail(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}>×</button><div className="preview">▤<b>{detail.format} PREVIEW</b><small>AUTHORIZED RENDITION</small></div><label>{detail.id}</label><h2>{detail.name}</h2><p>{detail.excerpt}</p><div className="facts"><span><small>COLLECTION</small><b>{detail.office}</b></span><span><small>ACCESS</small><b>{detail.access}</b></span><span><small>PAGES</small><b>{detail.pages||"Pending"}</b></span><span><small>OCR</small><b>{detail.confidence?`${detail.confidence}%`:"Queued"}</b></span></div><h3>Extracted concepts</h3><footer>{detail.tags.map(t=><span key={t}>{t}</span>)}</footer><div className="govern">◎ <p><b>Access event recorded</b><small>Visible under active role: {role}</small></p></div></aside></div>}
  </main>
}
